---
train_n_vars: [10]
test_n_vars: [10]
test_n_datasets: 10
additional_modules:
  - "./ldp_mechanism.py"
data:
  - n_observations_obs: 300
    n_observations_int: 0

    graph:
      - __class__: ErdosRenyi
        edges_per_var: [1.0]

    mechanism:
      - __class__: GaussianLDP

        epsilon: 100
        delta: 0.003
        clipping_scheme: robust_linear_clip
        base_mechanism:
          - __class__: LinearAdditive

            param:
              - __class__: SignedUniform
                low: 1.0
                high: 3.0

            bias:
              - __class__: Constant
                val: 0.0

            noise:
              - __class__: Uniform
                low: -3.0
                high: 3.0

            noise_scale:
              - __class__: Uniform
                low: 0.2
                high: 1.0

            n_interv_vars: 0
            interv_dist:
              - __class__: SignedUniform
                low:  1.0
                high: 5.0